### ISSUE TITLE
APIs definitions are not embedded

### ISSUE THREAD

**Issue by mrsinham** [rvflash/awql#1]
## Steps:

* Compile binary
* Dont have sources cloned from repo

## Output:

>> awql -i xxx-xxx-xxx                                                                                 Err 1 {.../campaign/report}
ParserError.CONNECTION_FAILED (stat /home/vagrant/code/go/src/github.com/rvflash/awql/vendor/github.com/rvflash/awql-db/src: no such file or directory)

## Suggestion:

Embedded definitions with a lib directly into the binary or auto download them or generate go code from conf.

**Comment by rvflash** [comment]
Good idea. I will add it in the next release.

**Comment by rvflash** [comment]
Add with the version v1.1.5.
