### ISSUE TITLE
Can i export result to object or xml or somethings?

### ISSUE THREAD

**Issue by kokorolx** [rvflash/awql#4]
Is it still maintain?
Can i export result to object or xml or somethings?

**Comment by rvflash** [comment]
Hi @kokorolee,

As you can see, the last update added the latest Google Ads API version, so the project is updated and followed.

The AWQL command's helper gives you the response to export the result.
The option `-B` uses the CSV format to print the data and the option `-e` allows you to execute inline AWQL statement.

Example:
`awql -i "XXX-XXX-XXXX" -e "show full tables;" -B`

I hope it helps,

**Comment by kokorolx** [comment]
I found how to export file:
```
go run main.go -i 254-809-2245 -D YOUR_DEVELOPER_TOKEN -T YOY_OAUTH2_TOKEN -e "select CampaignId ADGROUP_PERFORMANCE_REPORT" -B > FILENAME.csv
```
it will export csv file.
Thanks @rvflash
